export enum CategoryEnum {
    CODING,
    BUILDING,
    INDEXING ,
    DEBUGING ,
    BROWSING ,
    RESEARCHING ,
    CODE_REVIEWING,
    RUNNING_TESTS,
    WRITING_TESTS,
    WRITING_DOCS,
    DESIGNING ,
    LEARNING,
}
